# This file was generated by GoReleaser. DO NOT EDIT.
cask "outline-cli" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "ca3ea3b325d6faa1125186405fa97ed5c18291b7f97cf0a58d82373e53f4452a"
      url "https://github.com/yudhiesh-oc/outline-cli/releases/download/v#{version}/outline-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fb265ab96b8ee6341ff280c7387b98b72764ba24cfadcf045507abe00e3c40fc"
      url "https://github.com/yudhiesh-oc/outline-cli/releases/download/v#{version}/outline-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bbd39ad50f3a84af9aeaf817f093623604922ce382ff7d1793d96477586e3c11"
      url "https://github.com/yudhiesh-oc/outline-cli/releases/download/v#{version}/outline-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2981464a00dd32713943b5b6e6753de7947c14e2deaddf4bfe0287018064ca93"
      url "https://github.com/yudhiesh-oc/outline-cli/releases/download/v#{version}/outline-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "outline-cli"
  desc "Command-line client for the Outline knowledge base"
  homepage "https://github.com/yudhiesh-oc/outline-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "outline"

  # No zap stanza required
end
